// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:MaxMind.GeoIP2.UnitTests.DeserializationTests.CanDeserializeCountryResponseNewtonsoftJson")]
[assembly: SuppressMessage("Blocker Code Smell", "S2699:Tests should include assertions", Justification = "<Pending>", Scope = "member", Target = "~M:MaxMind.GeoIP2.UnitTests.DeserializationTests.CanDeserializeInsightsResponseNewtonsoftJson")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MaxMind.GeoIP2.UnitTests.WebServiceClientTests.AddressNotFoundShouldThrowException(System.String,MaxMind.GeoIP2.UnitTests.WebServiceClientTests.ClientRunner,System.Type)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MaxMind.GeoIP2.UnitTests.WebServiceClientTests.AddressReservedShouldThrowException(System.String,MaxMind.GeoIP2.UnitTests.WebServiceClientTests.ClientRunner,System.Type)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MaxMind.GeoIP2.UnitTests.WebServiceClientTests.AuthenticationErrorShouldThrowException(System.String,MaxMind.GeoIP2.UnitTests.WebServiceClientTests.ClientRunner,System.Type)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MaxMind.GeoIP2.UnitTests.WebServiceClientTests.BadCharsetRequirementShouldThrowException(System.String,MaxMind.GeoIP2.UnitTests.WebServiceClientTests.ClientRunner,System.Type)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MaxMind.GeoIP2.UnitTests.WebServiceClientTests.BadContentTypeShouldThrowException(System.String,MaxMind.GeoIP2.UnitTests.WebServiceClientTests.ClientRunner,System.Type)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MaxMind.GeoIP2.UnitTests.WebServiceClientTests.EmptyBodyShouldThrowException(System.String,MaxMind.GeoIP2.UnitTests.WebServiceClientTests.ClientRunner,System.Type)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MaxMind.GeoIP2.UnitTests.WebServiceClientTests.IncorrectlyFormattedIPAddressShouldThrowException(System.String,MaxMind.GeoIP2.UnitTests.WebServiceClientTests.ClientRunner,System.Type)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MaxMind.GeoIP2.UnitTests.WebServiceClientTests.InsufficientFundsShouldThrowException(System.String,MaxMind.GeoIP2.UnitTests.WebServiceClientTests.ClientRunner,System.Type)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MaxMind.GeoIP2.UnitTests.WebServiceClientTests.InternalServerErrorShouldThrowException(System.String,MaxMind.GeoIP2.UnitTests.WebServiceClientTests.ClientRunner,System.Type)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MaxMind.GeoIP2.UnitTests.WebServiceClientTests.NoErrorBodyShouldThrowException(System.String,MaxMind.GeoIP2.UnitTests.WebServiceClientTests.ClientRunner,System.Type)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MaxMind.GeoIP2.UnitTests.WebServiceClientTests.OutOfQueriesShouldThrowException(System.String,MaxMind.GeoIP2.UnitTests.WebServiceClientTests.ClientRunner,System.Type)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MaxMind.GeoIP2.UnitTests.WebServiceClientTests.PermissionRequiredShouldThrowException(System.String,MaxMind.GeoIP2.UnitTests.WebServiceClientTests.ClientRunner,System.Type)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MaxMind.GeoIP2.UnitTests.WebServiceClientTests.SurprisingStatusShouldThrowException(System.String,MaxMind.GeoIP2.UnitTests.WebServiceClientTests.ClientRunner,System.Type)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MaxMind.GeoIP2.UnitTests.WebServiceClientTests.UndeserializableJsonShouldThrowException(System.String,MaxMind.GeoIP2.UnitTests.WebServiceClientTests.ClientRunner,System.Type)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MaxMind.GeoIP2.UnitTests.WebServiceClientTests.UnexpectedErrorBodyShouldThrowExceptionAsync(System.String,MaxMind.GeoIP2.UnitTests.WebServiceClientTests.ClientRunner,System.Type)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MaxMind.GeoIP2.UnitTests.WebServiceClientTests.WebServiceErrorShouldThrowException(System.String,MaxMind.GeoIP2.UnitTests.WebServiceClientTests.ClientRunner,System.Type)")]
[assembly: SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MaxMind.GeoIP2.UnitTests.WebServiceClientTests.WeirdErrorBodyShouldThrowExceptionAsync(System.String,MaxMind.GeoIP2.UnitTests.WebServiceClientTests.ClientRunner,System.Type)")]
