version: 2
updates:
  - package-ecosystem: nuget
    directories:
      - "**/*"
    schedule:
      interval: daily
      time: "14:00"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "14:00"
